import './globals.css'
import { Genos } from 'next/font/google'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'

const inter = Genos({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Genos&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <Sidebar />
        {children}
        
        </body>
    </html>
  )
}
